AnimationPointers:
	table_width 2, AnimationPointers
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw WeedleAnimation
	dw KakunaAnimation
	dw BeedrillAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw EkansAnimation
	dw ArbokAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw BuizelAnimation
	dw FloatzelAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw PlaceholderAnimation
	dw HonchkrowAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw PlaceholderAnimation
	dw CroagunkAnimation
	dw ToxicroakAnimation
	dw PlaceholderAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw PsyduckAnimation
	dw GolduckAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw WeavileAnimation
	dw PlaceholderAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw SylveonAnimation
	dw PorygonZAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw PlaceholderAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw PlaceholderAnimation
	dw CottoneeAnimation
	dw WhimsicottAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw KrabbyAnimation
	dw KinglerAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw PlaceholderAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw LarvestaAnimation
	dw ScytherAnimation
	dw VolcaronaAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw PlaceholderAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw PlaceholderAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw MimikyuAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw PlaceholderAnimation
	dw PolitoedAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw WyrdeerAnimation
	dw MisdreavusAnimation
	dw UnownAnimation
	dw PlaceholderAnimation
	dw GirafarigAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw DunsparceAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw OrthwormAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw PlaceholderAnimation
	dw SneaselAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw Porygon2Animation
	dw StantlerAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw KokopelliAnimation
	dw FarigirafAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw TreeckoAnimation
	dw GrovyleAnimation
	dw SceptileAnimation
	dw TorchicAnimation
	dw CombuskenAnimation
	dw BlazikenAnimation
	dw MudkipAnimation
	dw MarshtompAnimation
	dw SwampertAnimation
	dw PoochyenaAnimation
	dw MightyenaAnimation
	dw ZigzagoonAnimation
	dw LinooneAnimation
	dw WurmpleAnimation
	dw SilcoonAnimation
	dw BeautiflyAnimation
	dw CascoonAnimation
	dw DustoxAnimation
	dw LotadAnimation
	dw LombreAnimation
	dw LudicoloAnimation
	dw SeedotAnimation
	dw NuzleafAnimation
	dw ShiftryAnimation
	dw WingullAnimation
	dw PelipperAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw GalladeAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw SlakothAnimation
	dw VigorothAnimation
	dw SlakingAnimation
	dw AzurillAnimation
	dw SkittyAnimation
	dw DelcattyAnimation
	dw SableyeAnimation
	dw MawileAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw PlaceholderAnimation
	dw RoseliaAnimation
	dw PlaceholderAnimation
	dw GulpinAnimation
	dw SwalotAnimation
	dw WailmerAnimation
	dw WailordAnimation
	dw NumelAnimation
	dw CameruptAnimation
	dw TrapinchAnimation
	dw VibravaAnimation
	dw FlygonAnimation
	dw CacneaAnimation
	dw CacturneAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw ZangooseAnimation
	dw SeviperAnimation
	dw BarboachAnimation
	dw WhiscashAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw FroslassAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	dw PlaceholderAnimation
	assert_table_length NUM_POKEMON
